<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ERP_LeaveRequest_EarnedLeave</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>0e744ef4-91c8-42e4-be61-17b2247a2b29</testSuiteGuid>
   <testCaseLink>
      <guid>a17be824-4747-4fe6-a7ef-8798fa6b05a1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ERP_LeaveRequest_EarnedLeave_Apply</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d13345f-0179-4404-bc2a-a77878044051</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11bf7c87-535a-4b69-93e0-ba8d0f3d01d5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e39aee86-7a6e-47d7-9eb9-99e171664799</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ERP_LeaveRequest_EarnedLeave_Approval</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4478698e-7e50-4677-a77a-5360c3c2bfc8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d43954c-1bc2-4c02-804f-b9a0ed5414c5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bddf76ee-750f-46a4-9b5a-f1868f0a9fd1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_EarnedLeave_Apply_Statusl</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07dd26c3-dfb6-4dac-ba2f-83d0c3048458</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73634f54-2590-4535-bf47-e086e2e37bfa</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
