<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>LEAVEREQUEST_APPLY_APPROVAL_GOPI</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>b7428208-280b-4450-b945-9bb88a86b9b7</testSuiteGuid>
   <testCaseLink>
      <guid>f5d20518-713c-4fa4-926f-a3ca0cc694ca</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CasualLeave_Gopi_Apply</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5022b0f-48a4-4fbd-a4e3-0177255a8ebb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e57a31b2-ccf0-400b-9b4c-5fa923af642f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f132ea97-4c71-4b52-96cf-2380cf00419f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CasualLeave_Gopi_Approval</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2814596a-1977-47b0-9f3e-0f36908c5064</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae9c80c3-86e9-4258-9756-a92bd37be6fe</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
