<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__LeaveStartDate</name>
   <tag></tag>
   <elementGuidId>63c6c832-f6ea-4037-b64b-547f89b4f97c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtLeaveStartDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtLeaveStartDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7fabcc1a-7331-4a3d-b5f3-3da7daf239d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control date-picker hasDatepicker</value>
      <webElementGuid>32a1bb83-0da2-41fd-8e8e-0852ed6a0d03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtLeaveStartDate</value>
      <webElementGuid>ffe66338-64e4-4ddc-a6bd-5427e70dd8d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LeaveStartDate</value>
      <webElementGuid>630a32f3-8e0b-46f1-b00e-e2b500886827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>GetToDate()</value>
      <webElementGuid>663bb5d5-36ce-44bc-8cdf-3adb2079c6e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>e35d081b-6801-45c4-8d8d-7344e30f96fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1e435263-75e1-4712-93fb-85df6bb1b387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtLeaveStartDate&quot;)</value>
      <webElementGuid>8aedaf01-3d72-47f6-8a90-991ca6446eb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtLeaveStartDate']</value>
      <webElementGuid>cf05444d-28f0-4b50-aeb4-ff863da2cdd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-container']/div[2]/form/div/div[2]/div[3]/div/div/div/div/div/div/div/fieldset/div[3]/div/input</value>
      <webElementGuid>0ce7c391-2db1-4ec5-8010-b2958329eb11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/fieldset/div[3]/div/input</value>
      <webElementGuid>772bcf14-9dd8-44ed-953c-b29c8d052d7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtLeaveStartDate' and @name = 'LeaveStartDate' and @type = 'text']</value>
      <webElementGuid>e020aa0a-491e-4cad-87fc-08cf098722f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
