<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__file</name>
   <tag></tag>
   <elementGuidId>6178134b-40a0-4ada-b5d2-8cfe8e7e8830</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'file' and @id = 'file' and @name = 'file']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#file</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fe9b66f5-4a15-49b2-abab-fcbf8cbaf3ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>2e93c4ce-0404-4233-9ad5-dd13b8470542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>e2b035dc-fbda-41cf-9101-ed289a70a428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>application/pdf</value>
      <webElementGuid>2525fa40-61ed-4012-85fb-e0231363c465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>43fa98c2-c225-41c2-8990-8e7062630808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;file&quot;)</value>
      <webElementGuid>e3ef6941-3451-4eba-91fb-53d66f63ef24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='file']</value>
      <webElementGuid>67498d1a-e6dd-4efc-bb7f-6cd9e03d63f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='showformedicalgroundsrequest1']/input</value>
      <webElementGuid>4c02a8ec-b36c-4152-a787-2338b806bdb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/fieldset/div[5]/div/input</value>
      <webElementGuid>1a88182d-8288-45d9-86bd-f7d6d86ee8d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'file' and @name = 'file']</value>
      <webElementGuid>029e86c1-c5fa-4703-987c-a97632f9c976</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
