<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Choose Action_Actionstyle</name>
   <tag></tag>
   <elementGuidId>8986cb08-3cbc-4af7-94eb-5177a112fed4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='SUBMIT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.Actionstyle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd5ae300-3490-4a1d-aa9e-87a060c928db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>a1eb7bac-296e-493b-9849-f09b26697e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Actionstyle</value>
      <webElementGuid>8c6a2d02-a6fd-4829-888d-d846e28e52a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>SUBMIT</value>
      <webElementGuid>7ad6dc1b-499b-4c99-b339-690b7b4049f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>LogData('7~F')</value>
      <webElementGuid>57f2ea67-5f31-4c39-8365-0684743c0d58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ulAction&quot;)/li[1]/input[@class=&quot;Actionstyle&quot;]</value>
      <webElementGuid>fe264ae2-426e-4e5f-a290-fb0e7119da80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='SUBMIT']</value>
      <webElementGuid>f478c395-61ff-4870-b3e7-499d9a942a62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ulAction']/li/input</value>
      <webElementGuid>02fe8daa-9da9-474d-9b8b-9e17039eca4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>4fe87e77-d0ac-446b-9647-61ea990eb154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>ad2360b9-4102-4504-a0a6-157387dc0956</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
