<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Leave Request Details_New Leave Request</name>
   <tag></tag>
   <elementGuidId>bea5cfff-57ee-4b07-81fa-5fab05ee68f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnNewLeaveRequest']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnNewLeaveRequest</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ec41205e-a6f8-428c-b054-f3df997042b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnNewLeaveRequest</value>
      <webElementGuid>06e5d507-f4a1-4c2f-85b8-e8f9a2796c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2cbd5adb-1042-4191-b634-81730ae60256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success pull-right</value>
      <webElementGuid>0505863a-5794-43ef-adce-a9eb3c92597c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>New Leave Request</value>
      <webElementGuid>c504384e-3c12-4294-8640-5e0524693d75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Request</value>
      <webElementGuid>ac23e2f5-766f-44aa-8ada-d4a25c0ded40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnNewLeaveRequest&quot;)</value>
      <webElementGuid>45c971e5-ce10-4bb2-af1c-47d38a44f870</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnNewLeaveRequest']</value>
      <webElementGuid>aa88f2c2-4395-46ab-aa9b-ab21e87a6444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-container']/div[2]/form/div/div[2]/div[2]/h1/input</value>
      <webElementGuid>ce8be92d-99a7-454b-a2f5-9861f1966de0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/input</value>
      <webElementGuid>7fea4e0a-1667-4d9c-bf7e-6368ae891c62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'btnNewLeaveRequest' and @type = 'button' and @name = 'New Leave Request']</value>
      <webElementGuid>8821409c-8920-47ca-b345-a7c0751e17be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
