<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Inbox</name>
   <tag></tag>
   <elementGuidId>e94fcd2a-5a0f-4beb-9690-e9d0693832f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='Modules']/li[11]/ul/li/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.submenu.can-scroll > li.hover.hover-show.hover-shown > a > span.menu-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fda73db4-8491-40f3-95f3-483432bb923d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-text</value>
      <webElementGuid>fd9f3f21-1b5e-4b10-8668-13dfbac9adbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Inbox</value>
      <webElementGuid>10d2ec7c-1494-4bfb-9160-c2550f715ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Modules&quot;)/li[@class=&quot;hover hover-show hover-shown&quot;]/ul[@class=&quot;submenu can-scroll&quot;]/li[@class=&quot;hover hover-show hover-shown&quot;]/a[1]/span[@class=&quot;menu-text&quot;]</value>
      <webElementGuid>7521299d-3449-4baa-b8c6-cb9831289e95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='Modules']/li[11]/ul/li/a/span</value>
      <webElementGuid>0719265b-2c80-4dd3-b249-6823276a8278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approval Inbox'])[1]/following::span[1]</value>
      <webElementGuid>69e8c733-4618-4ed6-a045-d69f741d510c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Policy And Procedure'])[1]/following::span[2]</value>
      <webElementGuid>d355e93b-f962-40a2-9a46-0d11f0c96d03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Support'])[1]/preceding::span[1]</value>
      <webElementGuid>5bf59df4-d622-47cc-a2c7-da372b7bb01e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ticket Summary'])[1]/preceding::span[2]</value>
      <webElementGuid>acb70d3c-4318-45a7-8178-d70ed6da80fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Inbox']/parent::*</value>
      <webElementGuid>54bb3e41-d9a5-48c3-b762-203e3f95f6df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[11]/ul/li/a/span</value>
      <webElementGuid>b742e7c3-96d8-4d3c-a375-6214309eb308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Inbox' or . = 'Inbox')]</value>
      <webElementGuid>e0508e4c-cfcf-4b18-bdbf-5e2d8009ef3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
