<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Choose Action_Actionstyle</name>
   <tag></tag>
   <elementGuidId>ae9961c3-8b33-46b5-bb94-45b2a00cf88c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='SUBMIT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.Actionstyle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>07f9f113-cebf-4618-91e6-2fbabcece19b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>070af887-41fe-4d19-b3c5-4803cc0d4b47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Actionstyle</value>
      <webElementGuid>b3a4fc70-bf3b-44ee-aaf3-af0978bd8130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>SUBMIT</value>
      <webElementGuid>4131cbe1-d099-45ed-9182-88c07b790d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>LogData('7~F')</value>
      <webElementGuid>41202fc1-232f-44e7-b6a7-25050d361316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ulAction&quot;)/li[1]/input[@class=&quot;Actionstyle&quot;]</value>
      <webElementGuid>7c261c29-ee57-4ecf-beaa-0cc29db62eb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='SUBMIT']</value>
      <webElementGuid>17eea0ff-0961-4d88-b7e0-44dfbad49324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ulAction']/li/input</value>
      <webElementGuid>4e7fc657-907e-409c-83db-34614cd67698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>3a2feab9-c34d-499f-9130-64abe081db03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>9f690e1f-836a-4842-8522-631bb2f83adb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
