<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__LeaveEndDate</name>
   <tag></tag>
   <elementGuidId>4a31888a-ed4b-4c65-9843-84324032413a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtLeaveEndDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtLeaveEndDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce3b87ca-55b2-490b-9818-5dde2238b31b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>645c0ad0-679a-480e-91d9-424ec1cf2636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control date-picker hasDatepicker</value>
      <webElementGuid>363b4ca7-decb-4bd8-92bd-142ee2610735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtLeaveEndDate</value>
      <webElementGuid>0decbbf3-76c4-4e9d-b66e-c0c1f937b633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LeaveEndDate</value>
      <webElementGuid>a19b850c-426a-4cb5-9786-ad720b00e1c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>OnClickTotalDays()</value>
      <webElementGuid>e2cd8a91-99d3-45e6-b89d-49a30dd0e629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ce213f7e-7b6a-4b03-8105-4c53e573957f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>d7de0d0d-7faa-44ad-aee8-bb8d392834f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2818cb98-a361-449a-bc3c-f04fbb404c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtLeaveEndDate&quot;)</value>
      <webElementGuid>808403a9-bc40-4f09-bffb-90c7217c3c01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtLeaveEndDate']</value>
      <webElementGuid>c763d0be-de29-49d7-900f-408da260ef15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='showonloadclick4']/div/input</value>
      <webElementGuid>20204e7e-01b6-40b8-8710-ca884a9a55e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>f6a3ccae-8e8f-4357-b196-f4e08537f80a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtLeaveEndDate' and @name = 'LeaveEndDate' and @type = 'text']</value>
      <webElementGuid>d0e080b2-b39f-45b7-a6ca-737880ecd13c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
