<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_-Select-</name>
   <tag></tag>
   <elementGuidId>3a0f63a1-7038-4c75-8baa-c0c2cf103f22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ddlLeaveType_chosen']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ddlLeaveType_chosen > a.chosen-single</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fd785469-b804-45c2-a645-1b34dbb392f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chosen-single</value>
      <webElementGuid>ebf4f793-e5ff-409c-9e0d-80051c69a2be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
  -Select-
  
</value>
      <webElementGuid>7a349ab1-0dea-4df4-a608-bd8550a0c4ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ddlLeaveType_chosen&quot;)/a[@class=&quot;chosen-single&quot;]</value>
      <webElementGuid>45af40ed-1668-4259-94ed-3c3aa5473cef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ddlLeaveType_chosen']/a</value>
      <webElementGuid>fbe26dea-e6b5-4b31-8b73-be93e1fcf49a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::a[1]</value>
      <webElementGuid>c66d1dfe-7a48-4234-8d89-1bcdbcdf5c3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-Select-'])[7]/preceding::a[1]</value>
      <webElementGuid>dd1e649d-5b8a-4ad4-b0bd-3e6ade2c5555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a</value>
      <webElementGuid>05dd1881-9f3d-4866-a121-8f556036597d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '
  -Select-
  
' or . = '
  -Select-
  
')]</value>
      <webElementGuid>00d5003a-74ce-4457-9f72-d896bcde4a7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
