<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Choose Action_Actionstyle</name>
   <tag></tag>
   <elementGuidId>81b0911d-eb94-4491-ab12-41e77eadecde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='SUBMIT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.Actionstyle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>83e6115e-e592-4dcd-aebf-2963c87e5c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d2a18767-a475-4e1a-8aab-449599dae7c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Actionstyle</value>
      <webElementGuid>994a06c7-477f-45dd-924f-bfc8f81956a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>SUBMIT</value>
      <webElementGuid>7cac027a-1334-48f7-925e-fdcab8bcec4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>LogData('7~F')</value>
      <webElementGuid>a3fa69ff-c812-4506-b030-5aaa83002e42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ulAction&quot;)/li[1]/input[@class=&quot;Actionstyle&quot;]</value>
      <webElementGuid>c1fa17ab-fc75-40ce-bd33-6645b5068d90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='SUBMIT']</value>
      <webElementGuid>59a0476f-2c73-4e70-9c69-2cba4fd958b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ulAction']/li/input</value>
      <webElementGuid>02e7fe0b-ae01-433f-adb5-8ba60da227b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>7e9f4fb4-140c-404d-9491-2ebcbb01c9f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>d59be21d-fbc6-42d1-9347-c15a070e9650</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
