<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LeaveStartDate</name>
   <tag></tag>
   <elementGuidId>75e07bae-0956-4cad-91b2-dea4087b710d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtLeaveStartDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtLeaveStartDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e8e84589-63b3-4b11-bcc6-722970d3e623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control date-picker hasDatepicker</value>
      <webElementGuid>8930d253-59b5-4c28-8480-e5100aee8ea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtLeaveStartDate</value>
      <webElementGuid>0f0f1622-1a21-4207-869e-f06b9c7c3142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LeaveStartDate</value>
      <webElementGuid>3cdc09d2-b73c-4651-acf3-41d05a8cadc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>GetToDate()</value>
      <webElementGuid>167a8353-b3e6-4e1b-9afd-055ced5d1643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>44c10a09-09cf-4154-9694-50f73f3d3a7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>54530cb5-0bfc-4fda-ac30-fa8ea9a2dba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtLeaveStartDate&quot;)</value>
      <webElementGuid>3ba72157-059f-4d79-b922-fceef8233083</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtLeaveStartDate']</value>
      <webElementGuid>1d84e988-ab09-4e6b-8028-38d11f0f0dc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-container']/div[2]/form/div/div[2]/div[3]/div/div/div/div/div/div/div/fieldset/div[3]/div/input</value>
      <webElementGuid>9795baeb-fd9a-4d53-8a25-585a2507b974</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/fieldset/div[3]/div/input</value>
      <webElementGuid>7153508a-53ca-497d-940c-2559f0507236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtLeaveStartDate' and @name = 'LeaveStartDate' and @type = 'text']</value>
      <webElementGuid>646fb5ba-c89d-45ee-aa02-dcb22c73042f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
