<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Leave Request Details_New Leave Request</name>
   <tag></tag>
   <elementGuidId>a22a97d4-e2d7-4fb3-8a4c-5338e9a2addc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnNewLeaveRequest']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnNewLeaveRequest</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3869c629-fbc2-4acf-bb12-f39c3acc901e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnNewLeaveRequest</value>
      <webElementGuid>ca344aa7-2711-4a51-a5a9-7aca97981c61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>44fe0c91-df4d-49e6-aab4-c096b3d18e9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success pull-right</value>
      <webElementGuid>e9a1a083-58cd-40d4-aa17-7ecb4f5f9e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>New Leave Request</value>
      <webElementGuid>b520d0c9-2272-4992-b1be-6e50a7f3bcbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Request</value>
      <webElementGuid>550ef0df-0ef1-42ff-9a2f-a60420ad6059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnNewLeaveRequest&quot;)</value>
      <webElementGuid>0e9dea88-5b9c-4941-9e15-46a4c57c2af5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnNewLeaveRequest']</value>
      <webElementGuid>304e37c1-642f-4688-8f07-7d3d2c5bcc1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-container']/div[2]/form/div/div[2]/div[2]/h1/input</value>
      <webElementGuid>5de84033-4db8-47d2-9c94-d35a49f4f693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/input</value>
      <webElementGuid>195bd128-6b64-4d02-a8cd-2d0f0051f518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'btnNewLeaveRequest' and @type = 'button' and @name = 'New Leave Request']</value>
      <webElementGuid>1ce42536-eba7-43c4-9e32-3b166ea43d78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
