<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__LeaveStartDate</name>
   <tag></tag>
   <elementGuidId>cd5699c1-6daf-4410-9e42-7beaef140bc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtLeaveStartDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtLeaveStartDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fab25331-50b9-41b8-a7a6-0c89ce62fbfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control date-picker hasDatepicker</value>
      <webElementGuid>48f6466c-011e-4d1d-a41f-4e0ced974f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtLeaveStartDate</value>
      <webElementGuid>5b009399-54dc-41ca-bb51-f43112d83473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LeaveStartDate</value>
      <webElementGuid>7fd7fcd8-5caf-4bda-affa-272d3e612237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>GetToDate()</value>
      <webElementGuid>ab47a9cc-7ea0-4e67-8a05-baa1ea519ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>f391c6ba-7163-489b-8cb8-73add5063684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f1f82596-3fe5-434d-b69f-958a17bff899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtLeaveStartDate&quot;)</value>
      <webElementGuid>66ca3bb9-affb-4d47-b884-8f63e09e8ecb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtLeaveStartDate']</value>
      <webElementGuid>271971a9-6410-4747-adad-69da0e03e4e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-container']/div[2]/form/div/div[2]/div[3]/div/div/div/div/div/div/div/fieldset/div[3]/div/input</value>
      <webElementGuid>b1973818-5c65-4a76-8b53-27bc66af53cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/fieldset/div[3]/div/input</value>
      <webElementGuid>13c1878b-b816-4b33-a739-bbd9de80b189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtLeaveStartDate' and @name = 'LeaveStartDate' and @type = 'text']</value>
      <webElementGuid>f72f5d9b-541a-47c6-b79c-d37711d99d0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
