<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Choose Action_Actionstyle</name>
   <tag></tag>
   <elementGuidId>8843d063-7ae7-47a1-9fc1-16e5d7b746b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='APPROVE']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.Actionstyle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bc48ea30-f36c-4d61-98cb-143f55cc1585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>438c780c-e10a-41ef-8ef7-c71c09129f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Actionstyle</value>
      <webElementGuid>5f2329a3-a216-4c06-a165-2557071ab993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>APPROVE</value>
      <webElementGuid>1bed7187-8f2f-45e6-93cf-6fd57dc27ce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>LogData('2')</value>
      <webElementGuid>bd17c43a-41e6-4c87-9510-6a1f9e010baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ulAction&quot;)/li[1]/input[@class=&quot;Actionstyle&quot;]</value>
      <webElementGuid>e1ed36fa-f95c-460e-beda-5e5fa27fbf3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='APPROVE']</value>
      <webElementGuid>341232b0-77c0-4655-b3f4-1ef68850e1de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ulAction']/li/input</value>
      <webElementGuid>9d3807b0-0f5e-4c20-92b8-54e02e9b2bac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>bba25c5d-d231-4ef8-a8a6-8d503a7628e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>04df5c9a-cb14-4772-b49c-ae2d625864a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
