<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Leave Request Details_New Leave Request</name>
   <tag></tag>
   <elementGuidId>4e77ea9b-28ff-4253-9752-19646e5e1bc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnNewLeaveRequest']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnNewLeaveRequest</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0644fb5d-7a4b-4766-b93f-a599ab9bccd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnNewLeaveRequest</value>
      <webElementGuid>fe34f4dc-4c99-499c-bdf4-8996cf175023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>887aaf1e-01e3-4e5a-8be4-fbb73d75be2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success pull-right</value>
      <webElementGuid>de30d9b5-fa14-4ce5-b20f-bf5a85571d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>New Leave Request</value>
      <webElementGuid>6aea8ed9-9354-4fd6-a642-d1d2e77ff2a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Request</value>
      <webElementGuid>c3ad00a8-f589-4c26-a309-efc04eb30f10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnNewLeaveRequest&quot;)</value>
      <webElementGuid>217d14ab-778f-4513-adb0-1902152aa4bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnNewLeaveRequest']</value>
      <webElementGuid>40e3c349-7ac5-4154-adf2-116047709ffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-container']/div[2]/form/div/div[2]/div[2]/h1/input</value>
      <webElementGuid>818a64c7-fc2b-41c2-ad64-86b8da46394e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/input</value>
      <webElementGuid>a59dcb36-1067-4e0d-814a-8a0a0f3294eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'btnNewLeaveRequest' and @type = 'button' and @name = 'New Leave Request']</value>
      <webElementGuid>df4cc477-817d-4cf1-8d93-f93097837413</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
