<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__LeaveStartDate</name>
   <tag></tag>
   <elementGuidId>1906bff7-9b8e-4a7c-ac3d-faea6bc38eca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtLeaveStartDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtLeaveStartDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fbc890ae-9d14-4cbd-a71e-9d151e98d805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control date-picker hasDatepicker</value>
      <webElementGuid>331719d0-d38e-4c37-b597-822e8537d5eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtLeaveStartDate</value>
      <webElementGuid>b98741f8-9971-4541-9532-be5b38aa4860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LeaveStartDate</value>
      <webElementGuid>dd98b3ed-41e2-4dd5-8850-0715fb39dae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>GetToDate()</value>
      <webElementGuid>4e8104b0-7523-46c2-b027-d7235e24a2b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>b9264910-aa2b-441a-a452-fec83935ddfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>71e38253-c05b-4b29-a0b0-d3534194bd20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtLeaveStartDate&quot;)</value>
      <webElementGuid>24ea4997-45a7-42f6-bb7d-9542c6d32409</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtLeaveStartDate']</value>
      <webElementGuid>5b866898-c158-44bd-a957-56f88df93695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-container']/div[2]/form/div/div[2]/div[3]/div/div/div/div/div/div/div/fieldset/div[3]/div/input</value>
      <webElementGuid>28b35aa6-81ab-48bc-bd8b-63eba20f5d42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/fieldset/div[3]/div/input</value>
      <webElementGuid>ba62ea45-bf28-4e08-bf8c-f1efea8d6a7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtLeaveStartDate' and @name = 'LeaveStartDate' and @type = 'text']</value>
      <webElementGuid>1636ee79-a416-4f7c-a818-30403a970167</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
