<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__LeaveStartDate</name>
   <tag></tag>
   <elementGuidId>06d2ea79-0ec0-4ea2-8b03-b57c7fcb35d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtLeaveStartDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtLeaveStartDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e395d198-cf11-4957-861a-532a2b552a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control date-picker hasDatepicker</value>
      <webElementGuid>a6eb3c62-0550-43e0-a0d7-f1c1663aa684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtLeaveStartDate</value>
      <webElementGuid>06ef7079-87b0-49c9-b973-e1062310c555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LeaveStartDate</value>
      <webElementGuid>23de5f63-c39f-4a1c-a8cc-9efe85a7bb17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>GetToDate()</value>
      <webElementGuid>55cd880a-3281-44a9-8313-c605cffb2b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>e937d20a-5d49-4bf5-a655-478fde9cb276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9210097e-6a2b-4b8f-8ebd-e8c4d2c135c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtLeaveStartDate&quot;)</value>
      <webElementGuid>459d7c97-98ed-487e-9a9f-948644c51669</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtLeaveStartDate']</value>
      <webElementGuid>ffe463e5-648e-45ee-a4a2-8dac39afbba1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-container']/div[2]/form/div/div[2]/div[3]/div/div/div/div/div/div/div/fieldset/div[3]/div/input</value>
      <webElementGuid>633efd9c-7c98-4bff-9d1e-d2c191d829c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/fieldset/div[3]/div/input</value>
      <webElementGuid>79d3c500-4f84-436c-92c9-a7bc0b43d306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtLeaveStartDate' and @name = 'LeaveStartDate' and @type = 'text']</value>
      <webElementGuid>7e64fddd-d5e5-418c-9699-74c2598b06ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
