<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Choose Action_Actionstyle</name>
   <tag></tag>
   <elementGuidId>f4cf4900-5d3f-4707-a0ba-e6b74453ea4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='REJECT FOR TESTING']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.Actionstyle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b7c1d1db-4431-4c41-b790-33aa846787c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>572a3de4-5f96-442d-a4e0-8aac4c51bdc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Actionstyle</value>
      <webElementGuid>73dcd9f6-e047-47d7-8456-ab572c58f096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>REJECT FOR TESTING</value>
      <webElementGuid>30ec840f-e99d-4c35-b761-d15219f6e19e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>LogData('10~C')</value>
      <webElementGuid>92fbbc51-bce6-4c31-9c24-1b97c10ebe59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ulAction&quot;)/li[1]/input[@class=&quot;Actionstyle&quot;]</value>
      <webElementGuid>aa4eb7bc-5007-486e-ab30-3fdcc0d0597f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='REJECT FOR TESTING']</value>
      <webElementGuid>84f24068-2855-44f1-acf3-577bcee61ff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ulAction']/li/input</value>
      <webElementGuid>63ee9306-fdad-44a5-9c6a-c2ec03003acf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>1931d216-8694-4de3-aa51-04c23623ff5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>3b0d71ba-57aa-4eb3-9c6a-f5ba82865fe7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
