<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__LeaveEndDate - Copy (1)</name>
   <tag></tag>
   <elementGuidId>4626b80a-ce26-46bb-82f0-c505b7756df6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtLeaveEndDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtLeaveEndDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>86155355-144b-43d7-a451-6a81f20b5c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>11b72e92-5b20-421e-a6da-0be00174533e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control date-picker hasDatepicker</value>
      <webElementGuid>6f0577b8-ca88-436c-ac36-a90dd36671ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtLeaveEndDate</value>
      <webElementGuid>e28dbcd5-0206-49c8-adf4-f545afb16b3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LeaveEndDate</value>
      <webElementGuid>c992f8c8-fbd0-4270-a899-a74a34253a61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>OnClickTotalDays()</value>
      <webElementGuid>51309a4f-8da2-4275-9191-81329f635c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>380e0110-1c0b-4aab-9031-bb85fa714f90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>440cb3fa-6a6a-445f-95fc-9319ed26c35b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f3e2618c-eca2-442f-930a-b39f64b59347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtLeaveEndDate&quot;)</value>
      <webElementGuid>97fde5d5-3a26-4905-9be0-f93a5afadd3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtLeaveEndDate']</value>
      <webElementGuid>da30cba2-5538-4c65-b380-039cb6c8e633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='showonloadclick4']/div/input</value>
      <webElementGuid>c3531325-05e9-4ed1-9422-18ba1114013d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>09711769-1243-47a8-89ac-3fa12ddc5793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtLeaveEndDate' and @name = 'LeaveEndDate' and @type = 'text']</value>
      <webElementGuid>fef8356c-7763-46e2-bdcf-02e127feed8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
