<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login_LoginName</name>
   <tag></tag>
   <elementGuidId>a9fb3e19-addb-4779-8a37-544113932246</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtLoginName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtLoginName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b4425ddc-9eca-44b8-9523-def00b1649a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a5d83e6d-50b0-44c7-8adf-a4fac9b46a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input100</value>
      <webElementGuid>bcab980e-9a9a-44ac-8372-2fdd65a66a6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtLoginName</value>
      <webElementGuid>c4c377e1-77cc-4ba9-a7ff-5c3f51143a32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>ea40808e-8c0d-4f0f-909c-048bc67011d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LoginName</value>
      <webElementGuid>e6455840-367c-4758-8dc7-5bf9d595b75a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter User Name</value>
      <webElementGuid>5772e757-ca33-4bb4-9237-a46eaaab6497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>3ac04e7e-fd5b-4ce1-9e58-5a3a14dcb991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4f25fbd5-6e26-421d-9db4-c67b8eb12aad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtLoginName&quot;)</value>
      <webElementGuid>c0dceac6-f7b4-4a1b-b732-03e8f2c05e4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtLoginName']</value>
      <webElementGuid>dde8407d-a13e-428e-9563-66d2ed03a9d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>39a4bcb3-b80c-465e-9afb-f86bac5d5578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtLoginName' and @name = 'LoginName' and @placeholder = 'Enter User Name' and @type = 'text']</value>
      <webElementGuid>f3d4e2f9-8006-419d-ad17-b5b79bcdc793</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
