<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__LeaveEndDate</name>
   <tag></tag>
   <elementGuidId>4376c563-644b-442a-83c9-99da4f959c76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtLeaveEndDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtLeaveEndDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>feaca680-d085-478c-8d72-19c4bd46fc08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c49b8d14-2461-4d02-be09-5723eafbadd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control date-picker hasDatepicker</value>
      <webElementGuid>5a99af8c-aca7-4858-a406-afc2d64a082a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtLeaveEndDate</value>
      <webElementGuid>69a64726-2026-49c6-9308-dd58905adb29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LeaveEndDate</value>
      <webElementGuid>5cd3c011-671b-4afc-a591-b49ec36677a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>OnClickTotalDays()</value>
      <webElementGuid>31d048a9-c3d5-4fa4-b08c-c8bea3d7d229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ed262c12-8900-440d-8a19-02b8585e70b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>bacffdf5-2d91-420f-b7fc-65dfb9b1ff9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e58845ba-4a4c-4e4c-9e8e-3d46a0364a3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtLeaveEndDate&quot;)</value>
      <webElementGuid>56007c5b-b117-46e1-8f38-60406dd52a82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtLeaveEndDate']</value>
      <webElementGuid>b925338d-0ea1-4822-ae19-1fb8a8b55391</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='showonloadclick4']/div/input</value>
      <webElementGuid>0cb91ac8-3d90-42f4-9247-f231f1ef6a76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>80dd8106-bae7-4de9-a691-e34981b399dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtLeaveEndDate' and @name = 'LeaveEndDate' and @type = 'text']</value>
      <webElementGuid>ab7659c0-5f7b-4512-a095-31b540155da0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
