<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_000852  Druba  Rakshit</name>
   <tag></tag>
   <elementGuidId>f1c3b113-0f2e-48c2-9327-4ece29a1ffc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ddlEmpId_chosen']/div/ul/li[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>894d4919-77f8-4714-a4a0-4b6b3ed1c20f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active-result result-selected</value>
      <webElementGuid>0be5d4d0-6cdd-4baf-a633-5a7ff14907a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-array-index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>2c4e2633-a17e-4878-ac0d-33938ebdb9f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>000852 ~ Druba ~ Rakshit</value>
      <webElementGuid>e8fb6f71-8581-4178-866d-6e33b416e9ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ddlEmpId_chosen&quot;)/div[@class=&quot;chosen-drop&quot;]/ul[@class=&quot;chosen-results&quot;]/li[@class=&quot;active-result result-selected&quot;]</value>
      <webElementGuid>045b63f3-afca-41fe-a281-d0d3e13af7de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ddlEmpId_chosen']/div/ul/li[3]</value>
      <webElementGuid>b5c8235a-5170-4a0e-9f4c-ff5e1bd6fccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-Select-'])[2]/following::li[2]</value>
      <webElementGuid>fd356ecc-df97-49cc-972d-8a5b9bab3f3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::li[3]</value>
      <webElementGuid>ea6b0aea-6c2d-4c92-ba4b-347bf4305347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/preceding::li[41]</value>
      <webElementGuid>50d85b88-fd1f-4cad-b089-531636205e88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Designation'])[2]/preceding::li[41]</value>
      <webElementGuid>71f472d2-54be-4466-b961-f97aefb0e825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/div/div/ul/li[3]</value>
      <webElementGuid>e3978415-b40a-44a9-8816-b5b2830c86de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '000852 ~ Druba ~ Rakshit' or . = '000852 ~ Druba ~ Rakshit')]</value>
      <webElementGuid>58e7cf0d-facd-4c23-a93c-decf449117af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
