<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Leave Request Details_New Leave Request</name>
   <tag></tag>
   <elementGuidId>84fbee4c-8328-4c09-8d5c-7ad02a14220d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnNewLeaveRequest']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnNewLeaveRequest</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ee21abd2-300d-4488-acb8-4532907dbcf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnNewLeaveRequest</value>
      <webElementGuid>5c225d97-24a6-462e-8556-a23a8d0d89f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d58884bc-170d-4451-b578-523ebf7b7a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success pull-right</value>
      <webElementGuid>113a1454-f440-4893-b7c5-c239c927f333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>New Leave Request</value>
      <webElementGuid>b5b230de-fbc5-4e16-b0b4-90cdabb06292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Request</value>
      <webElementGuid>0a354776-d19b-4273-a3c0-5934cd97331f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnNewLeaveRequest&quot;)</value>
      <webElementGuid>fbf40691-fbd1-448a-968a-85a2ae5379b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnNewLeaveRequest']</value>
      <webElementGuid>b4dbba10-9b0b-4dd9-8800-6c34060a1c40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-container']/div[2]/form/div/div[2]/div[2]/h1/input</value>
      <webElementGuid>f581b270-af75-416b-a4ad-7b173f891019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/input</value>
      <webElementGuid>0c6b4943-2760-49bf-8e58-4e3c08136c37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'btnNewLeaveRequest' and @type = 'button' and @name = 'New Leave Request']</value>
      <webElementGuid>7809ca8b-6381-41a5-abdf-80b2186bab48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
